name: iris-dev
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pandas
  - scikit-learn
  - black
  - flake8
  - flake8-docstrings
  - flake8-bugbear
  - flake8-builtins
  - flake8-comprehensions
  - flake8-eradicate
  - flake8-print
  - isort
  - pep8-naming
