$schema: https://azuremlschemas.azureedge.net/latest/commandComponent.schema.json
name: train_model
display_name: TrainModel
description: Train the model on the data usually submitted by the transfrom component.
version: 1

type: command
inputs:
  transformed_data_dir:
    type: uri_folder
    description:
      Directory that contains both train.csv and test.csv files,
      typically generated during data transformation.
outputs:
  model_dir:
    type: uri_folder

code: ../src/
environment:
  description: 'this will be dynamically set by the pipeline configuration.'

command: >-
  python -m train
  --transformed_data_dir ${{inputs.transformed_data_dir}}
  --model_dir ${{outputs.model_dir}}