name: Python build validation
on:
  pull_request:
    types: [opened, synchronize]
  push:
  workflow_dispatch:

jobs:
  Build_Validation:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: iris-dev
          environment-file: mlops/iris/environments/dev-environment.yml
          auto-activate-base: false

      - name: lint with flake8
        run: |
          flake8 .
        
